---
- name: Create group
  group: name="{{ item.name }}" gid="{{ item.uid }}"

- name: Create user
  user: name="{{ item.name }}" group="{{ item.name }}" uid="{{ item.uid }}" groups=admin

- name: Add public key
  authorized_key: user="{{ item.name }}" key="{{ lookup('file', item.name+'.pub') }}"
  ignore_errors: yes

